name: Deploy to Aliyun

on:
  push:
    branches:
      - main  # 或者您希望部署的其他分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print environment variables
        run: |
          echo "ALICLOUD_IP is ${{ secrets.ALICLOUD_IP }}"
          echo "SERVER_USER is ${{ secrets.ALICLOUD_USER }}"
          echo "DEPLOY_SSH_KEY is ${{ secrets.DEPLOY_SSH_KEY }}"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}  # 使用你的 SSH 私钥

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.ALICLOUD_IP }} >> ~/.ssh/known_hosts
  
      - name: Verify SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.ALICLOUD_USER }}@${{ secrets.ALICLOUD_IP }} "echo 'SSH connection successful!'"